<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="AddCounterToMessage" Id="{f098f86f-3ce0-4325-936e-91ba26331161}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION AddCounterToMessage : T_MaxString
VAR_INPUT
	counter : INT;
	message : T_MaxString;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[AddCounterToMessage := CONCAT('CRISTART ', 
					   CONCAT(INT_TO_STRING(counter), 
					   CONCAT(' ',
					   CONCAT(message, 
							 ' CRIEND')))); ]]></ST>
    </Implementation>
    <LineIds Name="AddCounterToMessage">
      <LineId Id="7" Count="0" />
      <LineId Id="10" Count="1" />
      <LineId Id="13" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>