<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="RadiansToDegrees" Id="{3bc61a45-1381-43a2-901e-4e4aca3a91d0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION RadiansToDegrees : LREAL
VAR_INPUT
	radians : LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[RadiansToDegrees := radians * 180 / GVL_RobotArmConstants.Pi;]]></ST>
    </Implementation>
    <LineIds Name="RadiansToDegrees">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>